[package]
name = "tucan-plus-api"
license = "AGPL-3.0-or-later"
edition = "2024"
version = "0.1.2"
rust-version = "1.85.1"

[dependencies]
axum = { version = "0.8.1", features = ["macros"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
utoipa = "5"
serde = { version = "1.0", features = ["derive"] }
utoipa-swagger-ui = { version = "9", features = ["axum", "vendored"] }
tucan-connector = { path = "../tucan-connector" }
utoipa-axum = "0.2"
tucan-types = { path = "../tucan-types" }
axum-extra = { version = "0.10.0", features = ["cookie"]}
serde_json = "1.0.133"
tower-http = { version = "0.6.6", features = ["cors"] }
tower = "0.5.2"
env_logger = "0.11.8"