[package]
name = "tucan-plus-planning"
license = "AGPL-3.0-or-later"
edition = "2024"
version = "0.1.2"
rust-version = "1.86"

[dependencies]
tucan-types = { path = "../tucan-types" }
futures-util = { version = "0.3", features = ["io"] }
serde_json = "1"
serde = { version = "1", features = ["derive"] }
async-compression = { version = "0.4.27", features = ["brotli", "all-implementations"] }
tokio = { version = "1", features = ["io-util"] }
log = { version = "0.4" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
itertools = "0.14"

[dev-dependencies]
tucan-connector = { path = "../tucan-connector" }
dotenvy = "0.15"
tucan-plus-worker = { path = "../tucan-plus-worker" }
