[package]
name = "tucan-plus-worker"
version = "0.1.0"
edition = "2024"

[dependencies]
log = { version = "0.4", features = ["max_level_debug", "release_max_level_warn"] }
diesel = { version = "2.3.2", features = ["sqlite", "returning_clauses_for_sqlite_3_35", "time", "r2d2"] }
diesel_migrations = { version = "2.3.0", features = ["sqlite"] }
tucan-types = { path = "../tucan-types" }
tokio = { features = [], version = "1" }
time = { version = "0.3.41", features = ["serde-human-readable", "wasm-bindgen", "macros"] }
serde = { version = "1", features = ["derive"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
libsqlite3-sys = { version = "0.35.0", features = ["bundled"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
# TODO FIXME: separate the rpc layer
sqlite-wasm-rs = { version = "0.4", default-features = false, features = ["bundled"] }
getrandom = { version = "0.3", features = ["wasm_js"] }
wasm-bindgen-futures = "0.4"
serde-wasm-bindgen = "0.6"
wasm-bindgen = { version = "0.2.104" }
web-sys = { version = "0.3", features = ["DedicatedWorkerGlobalScope", "MessageEvent", "Worker", "BroadcastChannel", "Document", "Window", "HtmlDocument", "NodeList", "HtmlSelectElement", "Blob", "Url", "BlobPropertyBag", "Worker", "WorkerOptions", "WorkerType", "AddEventListenerOptions", "EventTarget", "ErrorEvent", "FileList", "HtmlInputElement", "Navigator", "ServiceWorkerContainer", "ServiceWorker", "LockManager", "Lock", "BroadcastChannel"] }
js-sys = "0.3"
console_log = { version = "1", features = ["color"] }
typetag = "0.2"
erased-serde = "0.4"
enum_dispatch = "0.3.13"
# https://github.com/mitsuhiko/fragile/commit/47bb7220f4d1c422350bd95b5c43bf8e4a51f30f
fragile = { git = "https://github.com/mitsuhiko/fragile.git", features = ["future"] }
derive_more = { version = "2.0.1", features = ["from"] }
rand = "0.9.2"
