[package]
name = "tucan-plus-dioxus"
license = "AGPL-3.0-or-later"
edition = "2024"
version = "0.1.2"
rust-version = "1.86"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { git = "https://github.com/mohe2015/dioxus.git", branch = "my", features = ["launch", "devtools", "logger", "lib", "router" ] }
dioxus-desktop = { git = "https://github.com/mohe2015/dioxus.git", branch = "my", optional = true }
tucan-types = { path = "../tucan-types" }
log = { version = "0.4" }
reqwest = { version = "0.12.9", default-features = false, features = ["rustls-tls", "http2", "charset", "json"] }
serde_json = "1"
url = "2"
tucan-connector = { optional = true, path = "../tucan-connector" }
tucan-plus-planning = { path = "../tucan-plus-planning" }
tracing = "0.1.41"
plotters = { version = "0.3.7", default-features = false, features = ["svg_backend", "histogram"] }
keyring-core = { version = "0.5", optional = true }
git-version = "0.3"
futures = "0.3.31"
serde-wasm-bindgen = "0.6"
serde = { version = "1", features = ["derive"] }
tucan-plus-worker = { path = "../tucan-plus-worker" }
tokio = { version = "1" }
rand = "0.9.2"
time = { version = "0.3.41", features = ["serde-human-readable", "wasm-bindgen", "macros"] }
# https://github.com/mitsuhiko/fragile/commit/47bb7220f4d1c422350bd95b5c43bf8e4a51f30f
fragile = { git = "https://github.com/mitsuhiko/fragile.git", features = ["future"], optional = true }
num = "0.4"
itertools = "0.14"
async-compression = { version = "0.4.27", features = ["brotli", "all-implementations"] }
diesel = { version = "2.3.2", features = ["sqlite", "returning_clauses_for_sqlite_3_35", "time", "r2d2"] }
diesel_migrations = { version = "2.3.0", features = ["sqlite"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { features = ["macros", "rt", "rt-multi-thread"], version = "1" }
dbus-secret-service-keyring-store = { version = "0.2", features = ["crypto-rust"], optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
sqlite-wasm-rs = { version = "0.4", default-features = false, features = ["bundled"] }
cookie = "0.18"
getrandom = { version = "0.3", features = ["wasm_js"] }
web-extensions-sys = { optional = true, git = "https://github.com/mohe2015/web-extensions-sys", branch = "cookies" }
web-sys = { version = "0.3", features = ["Document", "Window", "HtmlDocument", "NodeList", "HtmlSelectElement", "Blob", "Url", "BlobPropertyBag", "Worker", "WorkerOptions", "WorkerType", "AddEventListenerOptions", "EventTarget", "ErrorEvent", "FileList", "HtmlInputElement", "Navigator", "ServiceWorkerContainer", "ServiceWorker", "LockManager", "Lock", "BroadcastChannel"] }
wasm-bindgen = { version = "0.2.104" }
wasm-bindgen-futures = "0.4"
android-native-keyring-store = { version = "0.3", optional = true }
js-sys = "0.3"
console_log = { version = "1", features = ["color"] }

# extension: target wasm and feature direct
# native: target native and feature direct
# dev: target wasm and feature api

[features]
direct = ["web", "dep:tucan-connector", "dep:web-extensions-sys"]
api = ["web", "dep:fragile"]
default = ["web"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop", "dep:dioxus-desktop", "dep:tucan-connector", "dep:keyring-core", "dep:dbus-secret-service-keyring-store"]
mobile = ["dioxus/mobile", "dep:dioxus-desktop", "dep:tucan-connector", "dep:keyring-core", "dep:android-native-keyring-store"]

[profile.wasm-dev.package.async-compression]
opt-level = 3

[profile.wasm-dev.package.brotli]
opt-level = 3