[package]
name = "tucant-tests"
license.workspace = true
edition.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
thirtyfour = "0.35.0"
tokio = { features = ["full"], version = "1.43.0" }
dotenvy = "0.15"

[lints]
workspace = true
