[package]
name = "tucan-types"
license = "AGPL-3.0-or-later"
edition = "2024"
version = "0.1.2"
rust-version = "1.86"

[dependencies]
serde = { version = "1", features = ["derive"] }
utoipa = "5"
axum-core = "0.5.0"
thiserror = "2"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "http2", "charset", "stream"] }
regex = { version = "1" }
dynosaur = "0.3"
